---
- hosts: all
  become: True
  roles: 
    - fedora-security
  vars: 
    fedora_version: 34
    fedora_user: user_name
    fedora_host: XXX.YYY.ZZZ.VVV    # IP Address or localhost
    fedora_private_key_file: ~/.ssh/demo-ssh
    fedora_port: 22