- block:
  - name: INSTALL RPM FUSION REPOS
    dnf:
      name: 
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
      state: present
    #vars:
    #  fedora_version: 34

  - name: VSCODE KEY
    ansible.builtin.rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: VSCODE REPO FILE
    shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

  - name: DOCKER
    get_url:
      url: https://download.docker.com/linux/fedora/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: REPO YARN
    get_url:
      url: https://dl.yarnpkg.com/rpm/yarn.repo
      dest: /etc/yum.repos.d/yarn.repo

  - name: POSGRESQL
    dnf:
      name:
        - https://download.postgresql.org/pub/repos/yum/reporpms/F-{{ fedora_version }}-x86_64/pgdg-fedora-repo-latest.noarch.rpm
      state: present

  - name: HASHICORP
    get_url: 
      url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
      dest: /etc/yum.repos.d/hashicorp.repo

  - name: KUBECTL REPO FILE
    shell: sh -c 'echo -e "[kubernetes]\nname=Kubernetes\nbaseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" > /etc/yum.repos.d/kubectl.repo'

  - name: WORKSTATION REPOS
    dnf:
      name: fedora-workstation-repositories
      state: latest

  - name: UPGRADE ALL PACKAGES
    dnf:
      name: "*"
      state: latest

  - name: INSTALL PACKAGES FOR KERNEL
    dnf: 
      name:
        - kernel-headers
        - kernel-devel
        - dnf-plugins-core
      state: latest

  - name: INSTALL PACKAGES GROUPS FOR OS
    dnf:
      name: 
        - "@Development Tools"
        - "@Development Libraries"
        - "@RPM Development Tools"
      state: latest
        
  - name: INSTALL USEFUL PACKAGES
    dnf:
      name: fedora-packager
      state: latest

  - name: UNINSTALL DEFAULT PACKAGES
    dnf: 
      name: 
        - xfburn
        - geany
        - pidgin
        - claws-mail
        - asunder
        - parole
        - pragha      
      state: absent

  - name: EXECUTE AUTOREMOVE COMMAND
    dnf:
      autoremove: yes

  - name: NEW FILE BASHRC
    template:
      src: bashrc-git-ps1-v3
      dest: /home/{{ fedora_user }}/.bashrc
      owner: "{{ fedora_user }}"
      group: "{{ fedora_user }}"
      mode: "0644"

#  - name: Rename file Repository
#    shell: mv /etc/yum.repos.d/_copr_phracek-PyCharm.repo /etc/yum.repos.d/PyCharm.repo
      